apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-sample
    app.kubernetes.io/part-of: sample-app-vn
  name: java-quarkus-sample
  namespace: vnambiar-hac
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: java-quarkus-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: java-quarkus-sample
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:vnambiar-hac-java-quarkus-sample
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
