apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-sample
    app.kubernetes.io/part-of: sample-app-vn
  name: java-quarkus-sample
  namespace: vnambiar-hac
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: java-quarkus-sample
    weight: 100
status: {}
